---
abstract: 'Lightning-fast URL fetcher'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  HTTP::Proxy: 0
  IO::Callback: 0
  IO::Socket::SSL: 0
  Net::DNS::Lite: 0
  Net::IDN::Encode: 0
  Plack: 0
  Plack::Middleware::Deflater: 0
  Starlet: 0
  Test::LeakTrace: 0
  Test::More: 0.96
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Requires: 0
  Test::TCP: 1.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Furl
no_index:
  directory:
    - example
    - inc
    - t
    - xt
recommends:
  Compress::Raw::Zlib: 0
  IO::Socket::SSL: 0
  Net::IDN::Encode: 0
requires:
  HTTP::Parser::XS: 0.11
  Mozilla::CA: 0
  perl: 5.8.1
resources:
  bugtracker: http://github.com/tokuhirom/Furl/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/tokuhirom/Furl/
version: 1.03
