---
abstract: 'Lightning-fast URL fetcher'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Request: 0
  HTTP::Response: 0
  IO::Socket::INET: 0
  Plack: 0.9949
  Test::More: 0.96
  Test::TCP: 1.06
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Furl
no_index:
  directory:
    - example
    - inc
    - t
    - xt
recommends:
  Compress::Raw::Zlib: 0
  IO::Socket::SSL: 0
  Net::IDN::Encode: 0
requires:
  HTTP::Parser::XS: 0.1
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
