---
abstract: 'Lightning-fast URL fetcher'
author:
  - 'Tokuhiro Matsuno <tokuhirom @gmail COM>'
build_requires:
  Test::Fake::HTTPD: 0
  Test::More: 0.96
  Test::Requires: 0
  Test::TCP: 1.06
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Furl
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
provides:
  Furl:
    file: lib/Furl.pm
    version: 2.11
  Furl::ConnectionCache:
    file: lib/Furl/ConnectionCache.pm
    version: 0
  Furl::HTTP:
    file: lib/Furl/HTTP.pm
    version: 2.11
  Furl::Headers:
    file: lib/Furl/Headers.pm
    version: 0
  Furl::Request:
    file: lib/Furl/Request.pm
    version: 0
  Furl::Response:
    file: lib/Furl/Response.pm
    version: 0
  Furl::ZlibStream:
    file: lib/Furl/ZlibStream.pm
    version: 0
recommends:
  Compress::Raw::Zlib: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  HTTP::Response: 0
  IO::Socket::SSL: 0
  Net::IDN::Encode: 0
requires:
  Class::Accessor::Lite: 0
  Encode: 0
  HTTP::Parser::XS: 0.11
  MIME::Base64: 0
  Mozilla::CA: 0
  Scalar::Util: 0
  Socket: 0
  Time::HiRes: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/Furl/issues
  homepage: https://github.com/tokuhirom/Furl
  repository: git://github.com/tokuhirom/Furl.git
version: 2.11
x_contributors:
  - 'Keiji, Yoshimi <walf443@gmail.com>'
  - 'Fuji, Goro <gfuji@cpan.org>'
  - 'lestrrat <lestrrat+github@gmail.com>'
  - 'Audrey Tang <audreyt@audreyt.org>'
  - 'mattn <mattn.jp@gmail.com>'
  - 'Fuji Goro <fuji.goro@dena.jp>'
  - 'bayashi <bayashi@cpan.org>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Kazuho Oku <kazuhooku@gmail.com>'
  - 'Fuji, Goro <g.psy.va@gmail.com>'
  - 's-aska <s.aska.org@gmail.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'ikasam_a <masaki.nakagawa@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
  - 'tokuhirom <tokuhirom@gmail.com>'
